### ISSUE TITLE
Failed to activate the package-control package

### ISSUE THREAD

**Issue by Chaetll** [idleberg/atom-package-control#2]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Pro
**Thrown From**: [package-control](https://github.com/idleberg/atom-package-control) package 0.12.3

### Stack Trace

Failed to activate the package-control package

```
At Unexpected token .

C:\Users\Chaetll\.atom\packages\package-control\lib\index-c7050a91.js:1
(function (exports, require, module, __filename, __dirname, process, global, Buffer) { return function (exports, require, module, __filename, __dirname) { "use strict";var e=require("atom"),t=require("stream"),i=require("http"),o=require("url"),r=require("https"),a=require("zlib"),n=require("buffer"),s=require("string_decoder");function c(e){return e

**Comment by idleberg** [comment]
Please upgrade to Atom 1.56 or later

**Comment by Sappay** [comment]
[Enter steps to reproduce:]

1. ...
2. ...

**Atom**: 1.55.0 x64
**Electron**: 6.1.12
**OS**: Microsoft Windows 10 Home
**Thrown From**: [auto-update-plus](https://github.com/idleberg/atom-auto-update-plus) package 0.11.1


### Stack Trace

Failed to activate the auto-update-plus package

```
At Unexpected token .

C:\Users\sapps\.atom\packages\auto-update-plus\lib\index-eb9d669a.js:16
function a(e,t){for(var i=0,a=t.length,n=e.length;i<a;i++,n++)e[n]=t[i];return e}var n=new(function(){function e(e){void 0===e&&(e={}),this.name=e.name,this.styleSheet="\n      background-color: "+(e.backgroundColor||"darkgrey")+";\n      border-radius: 2px;\n      color: "+(e.color||"white")+";\n      line-height: 1.5;\n      padding: 1px 4px;\n      text-shadow: 0 1px 0px rgba(0, 0, 0, 0.2);\n    "}return e.prototype.__console__=function(e){for(var t,i=[],a=1;a<arguments.length;a++)i[a-1]=arguments[a];(null===atom||void 0===atom?void 0:atom.inDevMode())&&(i.unshift("%c"+this.name+"%c",this.styleSheet,""),(t=window.console)[e].apply(t,i))},e.prototype.debug=function(){for(var e=[],t=0;t<arguments.length;t++)e[t]=arguments[t];this.__console__.apply(this,a(["debug"],e))},e.prototype.error=function(){for(var e=[],t=0;t<arguments.length;t++)e[t]=arguments[t];this.__console__.apply(this,a(["error"],e))},e.prototype.info=function(){for(var e

SyntaxError: Unexpected token .
    at new Script (vm.js:83:7)
    at NativeCompileCache.runInThisContext (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146297)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147181)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:146720)
    at /packages/auto-update-plus/lib/index.js:1:175)
    at /packages/auto-update-plus/lib/index.js:4:3)
    at Module.get_Module._compile (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:147404)
    at Object.value [as .js] (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:150952)
    at Module.load (internal/modules/cjs/loader.js:645:32)
    at Function.Module._load (internal/modules/cjs/loader.js:560:12)
    at Module.require (/app.asar/static/index.js:72:46)
    at require (internal/modules/cjs/helpers.js:16:16)
    at customRequire (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:1:736637)
    at requireModule (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:1122229)
    at Package.requireMainModule (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3509026)
    at Package.activateNow (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:3497010)
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:14:2607
    at Function.simpleDispatch (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1190181)
    at Emitter.emit (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:1191622)
    at PackageManager.triggerDeferredActivationHooks (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:384090)
    at ~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:382841
    at TextEditorRegistry.updateAndMonitorEditorSettings (~/AppData/Local/atom/app-1.55.0/resources/app/static/<embedded>:11:512989)
```

### Commands

```
  3x -0:28.6.0 settings-view:check-for-package-updates (atom-workspace.workspace.scrollbars-visible-always.theme-one-dark-syntax.theme-one-dark-ui)
```

### Non-Core Packages

```
atom-beautify 0.33.4 
atom-clock 0.1.18 
atom-elearnjs 0.6.7 
atom-emmet-css-in-js 0.2.0 
atom-formatter-jsbeautify 1.1.2 
atom-html-preview 0.2.7 
atom-ide-base 3.4.0 
atom-ide-code-format 1.0.2 
atom-ide-datatip 0.25.0 
atom-ide-definitions 0.4.2 
atom-ide-hyperclick 1.0.11 
atom-ide-markdown-service 2.1.0 
atom-ide-outline 3.2.0 
atom-ide-signature-help 0.16.0 
atom-ide-vue 1.4.6 
atom-jade 0.3.0 
atom-js-code-to-svg-to-preview 0.1.0 
atom-math 0.0.9 
atom-pug 0.2.0 
atom-smart-comments 0.2.1 
atom-ternjs 0.20.0 
atom-wrap-in-tag 0.6.0 
auto-update-plus 0.11.1 
autoclose-html 0.23.0 
beautify-handlebars 1.0.3 
browse 3.7.1 
build 0.70.0 
buildium 0.75.5 
busy-signal 2.0.1 
csslint 1.2.0 
ctrl-dir-scroll 0.2.5 
elias-comments 1.1.0 
emmet 2.4.3 
fast-eslint 4.15.0 
fold-comments 0.6.0 
git-review-comments 0.2.0 
html-tab 1.0.2 
html-tag-auto-complete 2.1.0 
html-to-css 0.2.2 
ide-html 0.7.0 
intentions 2.1.1 
jade-beautify 0.1.5 
js-patterns-atom-snippets 0.2.1 
jslint 1.5.1 
kite 0.206.0 
language-cup 1.1.2 
language-ejs 0.4.0 
linter 3.4.0 
linter-eslint 8.6.6 
linter-ui-default 3.4.1 
mariana-syntax 0.2.0 
markdown-to-html 0.5.0 
minimap 4.40.0 
moments-atom 0.2.0 
multi-cursor 3.0.0 
package-control 0.12.3 
pigments 0.40.6 
satisfy-dependencies 0.4.3 
scroll-through-time 0.3.1 
set-syntax 0.4.0 
sublime 0.9.0 
sublime-block-comment 0.5.1 
Sublime-Style-Column-Selection 1.7.5 
sublime-word-navigation 0.2.1 
sublimify 0.10.0 
tab-preview 0.8.0 
tag 0.5.0 
text-manipulation 0.6.0 
```

**Comment by idleberg** [comment]
As mentioned before, you need Atom v1.56 or later

https://github.com/idleberg/atom-package-control/blob/c434d61fdb231e9aca12621768306c66c91d7a5d/package.json#L32
